name: Run autotest on multiple OS and architectures

on:
  workflow_dispatch:

jobs:
  test:
    strategy:
      matrix:
        include:
          - os: macos-latest
            arch: aarch64
          - os: ubuntu-latest
            arch: x86_64

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.3'

    - name: Install gem
      run: gem install crudjt

    - name: Run autotest
      env:
        CRUDJT_AUTOTEST_ALLOWED: true
      run: ruby autotest.rb
